import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import "primeicons/primeicons.css";
import { PrimeReactProvider } from "primereact/api";
import Tailwind from "primereact/passthrough/tailwind";
import Header from "./header";
import Footer from "./footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <PrimeReactProvider
        value={{
          unstyled: true,
          pt: Tailwind,
        }}
      >
        <body className={inter.className}>
          <main>
            <Header></Header>
            <div className="mt-20">{children}</div>
            <Footer></Footer>
          </main>
        </body>
      </PrimeReactProvider>
    </html>
  );
}
